# Generated by Django 4.2 on 2023-07-06 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_rename_esssencial_categoria_essencial'),
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='categorias', to='perfil.categoria')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contas', to='perfil.conta')),
            ],
            options={
                'verbose_name': 'Valores',
            },
        ),
        migrations.DeleteModel(
            name='Valores',
        ),
    ]
