# Generated by Django 4.2.3 on 2023-07-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0002_valor_delete_valores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valor',
            options={'verbose_name_plural': 'Valores'},
        ),
    ]
