# Generated by Django 4.2 on 2023-07-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='esssencial',
            new_name='essencial',
        ),
    ]
